In [ ]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [ ]:
# 1D NumPy Array

marks = np.array([78, 85, 92, 67, 88])

print("1D Array:")
print(marks)

print("Shape:", marks.shape)
print("Data Type:", marks.dtype)

1D Array:
[78 85 92 67 88]
Shape: (5,)
Data Type: int64


In [ ]:
# 2D NumPy Array

student_marks = np.array([
    [78, 85, 92],
    [67, 88, 76],
    [90, 95, 89]
])

print("2D Array:")
print(student_marks)

print("Shape:", student_marks.shape)

2D Array:
[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)


In [ ]:
# NumPy Indexing

print("First element:", marks[0])
print("Second element:", marks[1])
print("Last element:", marks[-1])

print("First student, first subject:", student_marks[0, 0])
print("Second student, third subject:", student_marks[1, 2])

First element: 78
Second element: 85
Last element: 88
First student, first subject: 78
Second student, third subject: 76


In [ ]:
# NumPy Slicing

print("First three marks:")
print(marks[0:3])

print("\nLast three marks:")
print(marks[2:5])

print("\nFirst two students:")
print(student_marks[0:2])

print("\nFirst two subjects:")
print(student_marks[:, 0:2])

First three marks:
[78 85 92]

Last three marks:
[92 67 88]

First two students:
[[78 85 92]
 [67 88 76]]

First two subjects:
[[78 85]
 [67 88]
 [90 95]]


In [ ]:
# Mathematical Operations

print("Marks:", marks)

print("Sum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

Marks: [78 85 92 67 88]
Sum: 410
Mean: 82.0
Maximum: 92
Minimum: 67


In [ ]:
# Mathematical Operations on 2D Array

print("Student Marks:")
print(student_marks)

print("\nTotal of all marks:", np.sum(student_marks))
print("Average of all marks:", np.mean(student_marks))
print("Highest mark:", np.max(student_marks))
print("Lowest mark:", np.min(student_marks))

Student Marks:
[[78 85 92]
 [67 88 76]
 [90 95 89]]

Total of all marks: 760
Average of all marks: 84.44444444444444
Highest mark: 95
Lowest mark: 67


In [ ]:
# Python List vs NumPy Array

python_list = [10, 20, 30, 40]

numpy_array = np.array([10, 20, 30, 40])

print("Python List:")
print(python_list)

print("\nNumPy Array:")
print(numpy_array)

# Python list multiplication
print("\nPython List * 2:")
print(python_list * 2)

# NumPy array multiplication
print("\nNumPy Array * 2:")
print(numpy_array * 2)

Python List:
[10, 20, 30, 40]

NumPy Array:
[10 20 30 40]

Python List * 2:
[10, 20, 30, 40, 10, 20, 30, 40]

NumPy Array * 2:
[20 40 60 80]
